# Generated by Django 4.2.10 on 2025-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCommentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('International', 'International'), ('League', 'League'), ('Domestic', 'Domestic')], max_length=20, unique=True)),
                ('t20_count', models.PositiveIntegerField(default=0)),
                ('one_day_count', models.PositiveIntegerField(default=0)),
                ('test_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
