# Generated by Django 4.2.10 on 2025-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCommentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('good_comments', models.PositiveIntegerField(default=0)),
                ('bad_comments', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
