# Generated by Django 4.2.10 on 2025-04-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, null=True)),
                ('match_type', models.CharField(max_length=50)),
                ('match_format', models.CharField(blank=True, max_length=100, null=True)),
                ('series_name', models.CharField(max_length=255)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('flag1', models.ImageField(default=None, null=True, upload_to='images/')),
                ('flag2', models.ImageField(default=None, null=True, upload_to='images/')),
                ('match_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('innings_id', models.CharField(default=1, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, null=True)),
                ('InningsId', models.CharField(default=1, max_length=100)),
                ('OverNum', models.FloatField(max_length=100, null=True)),
                ('Event', models.CharField(max_length=100, null=True)),
                ('commentary', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=100, unique=True)),
                ('series_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('pub_time', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('story_type', models.CharField(max_length=50)),
                ('image_id', models.IntegerField()),
                ('context', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inningsId', models.CharField(default=1, max_length=10)),
                ('bat_team', models.CharField(max_length=200, null=True)),
                ('score', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('wickets', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matches')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.series'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('liked_by', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='match.oversummary')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='match.comment')),
            ],
        ),
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batsman_striker', models.JSONField()),
                ('batsman_non_striker', models.JSONField()),
                ('bowler_striker', models.JSONField()),
                ('bowler_non_striker', models.JSONField()),
                ('cur_overs_stats', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_ball_by_ball', to='match.matches')),
            ],
        ),
    ]
