# Generated by Django 4.2.10 on 2024-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, null=True)),
                ('series_id', models.CharField(max_length=100, null=True)),
                ('match_type', models.CharField(max_length=50)),
                ('series_name', models.CharField(max_length=255)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('match_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
