# Generated by Django 4.2.10 on 2024-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='flag1',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='matches',
            name='flag2',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
