# Generated by Django 4.2.10 on 2025-04-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BallByBall',
            new_name='StrikerInfo',
        ),
    ]
