# Generated by Django 4.2.10 on 2024-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_matches_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
