# Generated by Django 4.2.10 on 2024-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_oversummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='innings_id',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
    ]
