# Generated by Django 4.2.10 on 2024-05-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_matches_innings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversummary',
            name='commentary',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
