# Generated by Django 4.2.10 on 2024-05-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_oversummary_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='batting_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('wickets', models.IntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.matches')),
            ],
        ),
    ]
