# Generated by Django 4.2.10 on 2024-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_matches_batting_team_scoreboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='batting_team',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='bat_team',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
