# Generated by Django 4.2.10 on 2024-05-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_remove_matches_batting_team_scoreboard_bat_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='inningsId',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.matches'),
        ),
    ]
