# Generated by Django 4.2.10 on 2024-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_scoreboard_inningsid_alter_scoreboard_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversummary',
            name='InningsId',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
