# Generated by Django 4.2.10 on 2024-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_oversummary_inningsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='innings_id',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='oversummary',
            name='InningsId',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='inningsId',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
