# Generated by Django 4.2.10 on 2024-10-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=100, unique=True)),
                ('series_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='matches',
            name='series_id',
        ),
        migrations.AddField(
            model_name='matches',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='match.series'),
        ),
    ]
