# Generated by Django 4.2.10 on 2024-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_series_remove_matches_series_id_matches_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
