# Generated by Django 4.2.10 on 2024-10-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_alter_matches_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.series'),
        ),
    ]
