# Generated by Django 4.2.10 on 2024-10-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0019_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user_id',
        ),
    ]
