# Generated by Django 4.2.10 on 2024-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_remove_comment_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
