# Generated by Django 4.2.10 on 2024-10-31 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0022_comment_liked_by_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('pub_time', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('story_type', models.CharField(max_length=50)),
                ('image_id', models.IntegerField()),
                ('context', models.CharField(max_length=50)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.coverimage')),
            ],
        ),
    ]
