# Generated by Django 4.2.10 on 2024-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0023_coverimage_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversummary',
            name='commentary',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
