# Generated by Django 4.2.10 on 2024-10-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_alter_oversummary_overnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversummary',
            name='OverNum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
