# Generated by Django 4.2.10 on 2024-12-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0028_remove_story_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallByBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batsman_striker', models.JSONField()),
                ('batsman_non_striker', models.JSONField()),
                ('bowler_striker', models.JSONField()),
                ('bowler_non_striker', models.JSONField()),
                ('cur_overs_stats', models.TextField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_ball_by_ball', to='match.matches')),
            ],
        ),
    ]
